# Generated by Django 6.0 on 2026-01-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_productdetails_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='created_at',
            new_name='created',
        ),
    ]
